### PR TITLE
XW-440 Minify and uglify import-built.html

### PR DESCRIPTION
**Pull request by rogatty**
https://wikia-inc.atlassian.net/browse/XW-440

Fixes https://github.com/Wikia/style-guide/issues/83

It would look much better without using `/tmp/import-built.html` but there is an issue with gulp-vulcanize that prevents us from doing it the clean way, see https://github.com/Polymer/vulcanize/issues/203

/cc @kenkouot @lizlux

### CODE REVIEW

**Comment by tomasznapieralski** [comment]
LGTM

**Comment by rogatty** [comment]
@kenkouot @lizlux I'm not sure about git tags here.

`dev` branch (https://github.com/Wikia/style-guide/blob/dev/bower.json) has `v1.7.0` but at https://github.com/Wikia/style-guide/tags I can see that there are also `v1.7.1` and `v1.8.0`.

How exactly should I proceed after merging this branch so I can use it in https://github.com/Wikia/mercury/pull/1505?

**Comment by hakubo** [comment]
LGTM

**Comment by lizlux** [comment]
@rogatty, sorry about the tags issue. It should be cleaned up now. The latest tag and release should be at `v1.7.1`. You can delete `v1.8.0` if you still have it locally.

**Comment by lizlux** [comment]
LGTM

**Pull request merged**
