### PR TITLE
Update node-sass package to >2.0.1 allows npm install under osx

### PR DESCRIPTION
**Pull request by vforge**
```
>>> npm install
/
> node-sass@1.2.3 install /Users/v/Software/style-guide/node_modules/node-sass
> node scripts/install.js

Binary downloaded and installed at /Users/v/Software/style-guide/node_modules/node-sass/vendor/darwin-x64/binding.node

> node-sass@1.2.3 postinstall /Users/v/Software/style-guide/node_modules/node-sass
> node scripts/build.js

`darwin-x64` exists; testing
module.js:355
  Module._extensions[extension](this, filename);
                               ^
Error: Module did not self-register.
    at Error (native)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/v/Software/style-guide/node_modules/node-sass/lib/index.js:181:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! node-sass@1.2.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@1.2.3 postinstall script 'node scripts/build.js'.
npm ERR! This is most likely a problem with the node-sass package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls node-sass
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/v/Software/style-guide/gh-pages/npm-debug.log
```

Fixed with https://github.com/sass/node-sass/issues/569

### CODE REVIEW

**Comment by hakubo** [comment]
LGTM

**Comment by vforge** [comment]
Also forcing `gulp` to rebuild `dist` directory removed some vendor files.

**Comment by vforge** [comment]
ping @hakubo

**Comment by hakubo** [comment]
wow are we sure we should delete those? :)

**Comment by hakubo** [comment]
+1 −14,989 :)

**Comment by vforge** [comment]
@hakubo I've only started server (as described on main page), it rebuilded and removed not used assets :|

**Comment by lizlux** [comment]
I came across this same issue with this PR https://github.com/Wikia/style-guide/pull/53. What's the status of this change? Can we merge?

**Comment by bkoval** [comment]
+1 if it's tested and working :) ping @vforge

**Comment by vforge** [comment]
It was more a question of https://github.com/Wikia/style-guide/commit/940f55ef494ae8a3d376e5f70f8bc723f9ffad9c change - but I've only ran jekyll and it juist removed a bunch of files (whose should probably be in `.gitignore` anyway as those are re-build by jekyll.

If you think it's ok we can merge, ofc.

**Comment by vforge** [comment]
Or just revert last commit and merge.

**Comment by lizlux** [comment]
I'd like to do all of these things but break them up into smaller pieces. I created https://github.com/Wikia/style-guide/pull/54 for the library upgrades and https://github.com/Wikia/style-guide/pull/55 for the css changes. Then we can investigate cleaning up the `dist` folder in a separate commit.

**Comment by lizlux** [comment]
Merged https://github.com/Wikia/style-guide/pull/54.

**Comment by lizlux** [comment]
@vforge, this PR could still be useful for deleting those files so feel free to reopen if you'd like.

**Comment by vforge** [comment]
@lizlux Nope, I'm good, thank you very much!

**Pull request closed without merging**
